rm(list = ls())

## Load libraries ----
library(ggplot2)
library(scales)
library(gt)
library(googlesheets)
library(tidyr)
library(purrr)
library(readr)
library(stringr)
library(dplyr)
library(glue)
library(packcircles)
library(viridis)
library(ggiraph)
